server:
  port: 8760

spring:
  application:
    name: gateway
    loadbalancer:
      ribbon:
        enabled: false

info:
  app:
    name: 'addw'

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - routes
          - info